version: '3.8'

networks:
  go-network:
    driver: bridge

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - ./src:/app:delegated
    networks:
      - go-network
    environment:
      - 'DB_PORT=3306'
      - 'DB_HOST=go-mysql'

    depends_on:
      - go-mysql
      - go-phpmyadmin

  go-mysql:
    image: mariadb:10.6
    container_name: go-mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wanderdb
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - go-network

  go-phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: go-phpmyadmin
    networks:
      - go-network
    ports:
      - 8080:80
    environment:
      PMA_HOST: go-mysql
    depends_on:
      - go-mysql
